DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS authors;

CREATE TABLE  authors(
     author_id INT AUTO_INCREMENT PRIMARY KEY,
     name VARCHAR(250) NOT NULL
);

CREATE TABLE  books(
   id INT AUTO_INCREMENT PRIMARY KEY,
   author_id INT,
   FOREIGN KEY (author_id) REFERENCES authors(author_id),
   title VARCHAR(250) NOT NULL,
   priceOld  VARCHAR(250) DEFAULT NULL,
   price VARCHAR(250) DEFAULT NULL
);

